import React from "react";
import Modal from "./Modal.jsx";

const LOCAL_KEYS = [
  "activeReminder",
  "doseSchedule",
  "takenTimestamps",
  "medsTaken",
  "nextDoseTime",
  "overdueMap",
  "lastCheerMilestone",
  "isSupporter",
  "ownerId",
  "ownerName",
  "supporterName",
];

/**
 * Localized copy for the Privacy modal.
 * Edit strings here if you want to tweak wording later.
 */
const T = {
  English: {
    title: "Privacy Policy",
    quick:
      "Pill-AI does not collect or store personal data about you. Your questions are processed anonymously. Do not rely on Pill-AI for medical decisions—always consult a health professional.",
    hCollect: "What we collect",
    weCollect: [
      "No account is required. We do not ask for your name, email, or address.",
      "No medicine history is uploaded to our servers by the app.",
      "We do not intentionally collect any sensitive personal information.",
    ],
    hOnDevice: "What stays on your device",
    onDevice: [
      "Reminder setup (medicine name, duration/long-term, times per day, chosen times).",
      "Dose schedule and which doses you marked as taken.",
      "Progress counters and milestones for cheering.",
      "Support/cheer membership info you joined or created (IDs/names you entered).",
    ],
    noteLocal: "Stored using your browser’s localStorage on this device only.",
    hNotifications: "Notifications & permissions",
    notifications: [
      "To send reminders, the app asks your browser/phone for permission to show notifications.",
      "A push token is generated by your browser for this device. It is used only to deliver reminders you asked for.",
      "You can revoke notification permission anytime in your browser/device settings.",
    ],
    hSharing: "Sharing & third parties",
    sharing: [
      "We do not sell your data.",
      "Cheer Squad links you share are private to people you send them to.",
      "Aggregated, de-identified stats may be used to improve the prototype.",
    ],
    hChoices: "Your choices & control",
    choices: [
      "You can delete on-device data below (localStorage).",
      "You can disable notifications in your browser/device settings.",
      "You can remove supporters and invites at any time.",
    ],
    hMinors: "Minors",
    minors:
      "Pill-AI is a prototype for education/research. If you are under 16, use it with a parent/caregiver.",
    hSafety: "Safety disclaimer",
    safety:
      "Content is informational only and based on trusted NZ sources (e.g., Medsafe). It does not replace professional advice.",
    clearBtn: "🗑️ Clear my app data (local)",
    clearDone: "Local app data cleared.",
    confirm:
      "Clear local app data for this browser? This will reset reminders, progress, and supporter info stored on this device.",
  },

  "Te Reo Māori": {
    title: "Kaupapahere Tūmataitinga",
    quick:
      "Kāore a Pill-AI e kohikohi, e rokiroki rānei i ngā raraunga whaiaro mōu. Ka tukatukahia āu pātai ā-kāore he ingoa. Kaua e whakawhirinaki ki Pill-AI mō ngā whakatau haumanu—me ui tonu ki tētahi mātanga hauora.",
    hCollect: "He aha ka kohia e mātou",
    weCollect: [
      "Kāore he pūkete e hiahiatia ana. Kāore mātou e pātai mō tō ingoa, īmēra, wāhitau hoki.",
      "Kāore he hītori rongoā e tukuna ki ā mātou tūmau e te taupānga.",
      "Kāore mātou e kohikohi whakaaro ai i ngā pārongo tairongo.",
    ],
    hOnDevice: "Ngā mea ka noho ki tō pūrere",
    onDevice: [
      "Ngā tautuhinga whakamahara (ingoa rongoā, roanga/roa-tonu, ngā wā ia rā, ngā wā i tīpakohia).",
      "Te mahere horopeta me ngā horopeta i tohua e koe kua tangohia.",
      "Ngā kaute ahunga me ngā pae pae mō te whakakipakipa.",
      "Ngā mōhiohio mematanga Tautoko/Cheer i uru mai koe, i waihanga rānei (ID/ingoa i tāurua e koe).",
    ],
    noteLocal:
      "Ka rokirokia mā te localStorage o tō pūtirotiro, i tēnei pūrere anake.",
    hNotifications: "Ngā whakamōhiotanga me ngā whakaaetanga",
    notifications: [
      "Hei tuku whakamaumahara, ka tono te taupānga i tō pūtirotiro/waea kia whakaae ki ngā whakamōhiotanga.",
      "Ka waihangatia e tō pūtirotiro he tohu pana mō tēnei pūrere; mō ngā whakamaumahara anake te whakamahi.",
      "Ka taea e koe te whakakore i te whakaaetanga i ngā tautuhinga o tō pūtirotiro/pūrere i ngā wā katoa.",
    ],
    hSharing: "Tiritiri me ngā rōpū tuatoru",
    sharing: [
      "Kāore mātou e hoko i ō raraunga.",
      "He tūmataiti ngā hononga Cheer Squad ki te hunga ka tukuna e koe.",
      "Ka āhei pea te whakamahi tatauranga kua whakakotahitia, kua whakakore-ā-tangata hei whakapai i te tauira.",
    ],
    hChoices: "Ō kōwhiringa me te whakahaere",
    choices: [
      "Ka taea e koe te muku i ngā raraunga ā-pūrere (localStorage) i raro nei.",
      "Ka taea e koe te mono i ngā whakamōhiotanga i ngā tautuhinga o tō pūtirotiro/pūrere.",
      "Ka taea e koe te tango i ngā kaitautoko me ngā pōhiri i ngā wā katoa.",
    ],
    hMinors: "Tamariki",
    minors:
      "He tauira a Pill-AI mō te mātauranga/rangahau. Mēnā he iti iho i te 16 ō tau, whakamahia tahi me tētahi mātua/kaitiaki.",
    hSafety: "Whakakapinga haumaru",
    safety:
      "He mōhiohio whānui anake te ihirangi, nō ngā puna whaimana o Aotearoa (pērā i a Medsafe). Ehara i te whakakapi i ngā tohutohu a tētahi mātanga.",
    clearBtn: "🗑️ Muku aku raraunga taupānga (ā-roto anake)",
    clearDone: "Kua mukua ngā raraunga taupānga ā-roto.",
    confirm:
      "Muku i ngā raraunga taupānga ā-roto mō tēnei pūtirotiro? Ka tautuhi anō i ngā whakamahara, te ahunga, me ngā pārongo kaitautoko kei tēnei pūrere.",
  },

  Samoan: {
    title: "Faiga Fa‘alilolilo",
    quick:
      "E lē aoina pe teu e Pill-AI ni fa‘amatalaga patino e uiga iā te oe. E fa‘agasolo ou fesili i se auala e lē mafai ona iloa ai se tagata. Aua le fa‘alagolago i Pill-AI mo fa‘ai‘uga fa‘afoma‘i—ia fesili pea i se foma‘i.",
    hCollect: "O le ā mea matou te aoina",
    weCollect: [
      "E lē mana‘omia se teugatupe. E lē matou fesili mo lou igoa, īmeili, po o lou tuatusi.",
      "E lē siiina e le app se tala‘aga o vaila‘au i a matou ‘au‘aunaga.",
      "E lē matou taumafai e aoina fa‘amatalaga ma‘ale‘ale.",
    ],
    hOnDevice: "O mea e tumau i lau masini",
    onDevice: [
      "Fausiaga o fa‘amanatu (igoa o le vaila‘au, umi/umi-tumau, taimi i le aso, taimi na e filifilia).",
      "Kalena o inuga ma inuga na e fa‘ailogaina ua ‘Meds Taken’.",
      "Faitauga o le alualu i luma ma mailei mo le cheering.",
      "Fa‘amatalaga o sui/lagolago na e lesitala ai po o faia (ID/igoa na e tusia).",
    ],
    noteLocal:
      "E teu i le localStorage a le browser i lenei masini na o ia.",
    hNotifications: "Fa‘asilasilaga & fa‘atagaga",
    notifications: [
      "Ina ia lafo fa‘amanatu, e talosaga le app i lau browser/telefone le fa‘ataga e fa‘aali fa‘asilasilaga.",
      "E faia e lau browser se push token mo lenei masini; e fa‘aaogā na o le lafoina o fa‘amanatu na e talosagaina.",
      "E mafai ona e aveese le fa‘ataga i so‘o se taimi i seti a le browser/masini.",
    ],
    hSharing: "Fetufa‘a‘i & vaega lona tolu",
    sharing: [
      "E lē matou fa‘atauina au fa‘amatalaga.",
      "E tumau le fa‘alilolilo o so‘otaga Cheer Squad e te fa‘asoa atu i ē e te lafoina i ai.",
      "E ono fa‘aaogā fa‘amatalaga fa‘a‘aofai ma lē mafai ona iloa ai se tagata e fa‘aleleia ai le polokalame.",
    ],
    hChoices: "Lau filifiliga & pulea",
    choices: [
      "E mafai ona e tapeina fa‘amatalaga i le masini i lalo (localStorage).",
      "E mafai ona e tapē fa‘asilasilaga i seti a le browser/masini.",
      "E mafai ona e aveese lagolago ma valaaulia i so‘o se taimi.",
    ],
    hMinors: "Fanau laiti",
    minors:
      "O le Pill-AI o se fa‘ata‘ita‘iga mo a‘oa‘oga/su‘esu‘ega. Afai e i lalo ifo o le 16 lou matutua, fa‘aaogā fa‘atasi ma mātua/tausimai.",
    hSafety: "Fa‘aeteetega o le saogalemu",
    safety:
      "O mea o lo‘o tu‘uina mai e mo fa‘amatalaga lautele ma e fa‘avae i punaoa fa‘atuatuaina a Niu Sila (e pei o Medsafe). E lē suitulaga i fautuaga a se foma‘i po‘o se foma‘i vaila‘au.",
    clearBtn: "🗑️ Tape a‘u fa‘amaumauga (lenei masini)",
    clearDone: "Ua tape fa‘amaumauga o le app i lenei masini.",
    confirm:
      "Tape fa‘amaumauga o le app mo lenei browser? O le a toe seti fa‘amanatu, alualu i luma, ma fa‘amatalaga lagolago i lenei masini.",
  },

  Mandarin: {
    title: "隐私政策",
    quick:
      "Pill-AI 不会收集或存储你的个人数据。你的问题会以匿名方式处理。不要依赖 Pill-AI 做医疗决定——请始终咨询专业医护人员。",
    hCollect: "我们收集什么",
    weCollect: [
      "无需账号。我们不会索要你的姓名、邮箱或地址。",
      "应用不会把用药历史上传到我们的服务器。",
      "我们不会有意收集任何敏感个人信息。",
    ],
    hOnDevice: "哪些数据保存在你的设备上",
    onDevice: [
      "提醒设置（药名、时长/长期、每日次数、具体时间）。",
      "剂量日程以及你标记为已服用的记录。",
      "进度计数与里程碑（用于鼓励）。",
      "你创建或加入的支持/助威成员信息（你输入的 ID/姓名）。",
    ],
    noteLocal: "仅存储在此设备的浏览器 localStorage 中。",
    hNotifications: "通知与权限",
    notifications: [
      "为发送提醒，应用会向浏览器/手机请求通知权限。",
      "浏览器会为此设备生成推送令牌，仅用于发送你要求的提醒。",
      "你可随时在浏览器/设备设置中撤销通知权限。",
    ],
    hSharing: "共享与第三方",
    sharing: [
      "我们不会出售你的数据。",
      "你分享的加油小队链接仅对你发送给的人可见。",
      "我们可能使用汇总且去标识化的数据来改进原型。",
    ],
    hChoices: "你的选择与控制",
    choices: [
      "你可以在下方删除本机数据（localStorage）。",
      "你可以在浏览器/设备设置中关闭通知。",
      "你可以随时移除支持者和邀请。",
    ],
    hMinors: "未成年人",
    minors:
      "Pill-AI 是用于教育/研究的原型。如果你未满 16 岁，请在家长/监护人的陪同下使用。",
    hSafety: "安全声明",
    safety:
      "内容仅供参考，来源于新西兰可信渠道（如 Medsafe）。不能替代专业人士的建议。",
    clearBtn: "🗑️ 清除本机应用数据",
    clearDone: "已清除本机应用数据。",
    confirm:
      "清除此浏览器的本机应用数据？这会重置本设备上保存的提醒、进度和支持者信息。",
  },
};

export default function PrivacyPolicy({ isOpen, onClose, language }) {
  const L = T[language] || T.English;

  function clearLocal() {
    if (!window.confirm(L.confirm)) return;
    try {
      LOCAL_KEYS.forEach((k) => localStorage.removeItem(k));
      alert(L.clearDone);
    } catch (e) {
      console.warn("Clear local failed:", e);
    }
  }

  return (
    <Modal open={isOpen} onClose={onClose} title={L.title}>
      <div className="policy">
        <p style={{ marginTop: 0 }}>{L.quick}</p>

        <details open>
          <summary>✅ {L.hCollect}</summary>
          <ul>{L.weCollect.map((x, i) => <li key={i}>{x}</li>)}</ul>
        </details>

        <details>
          <summary>📱 {L.hOnDevice}</summary>
          <ul>{L.onDevice.map((x, i) => <li key={i}>{x}</li>)}</ul>
          <p style={{ marginTop: 8, fontSize: 13, color: "#666" }}>
            {L.noteLocal}
          </p>
        </details>

        <details>
          <summary>🔔 {L.hNotifications}</summary>
          <ul>{L.notifications.map((x, i) => <li key={i}>{x}</li>)}</ul>
        </details>

        <details>
          <summary>🤝 {L.hSharing}</summary>
          <ul>{L.sharing.map((x, i) => <li key={i}>{x}</li>)}</ul>
        </details>

        <details>
          <summary>⚙️ {L.hChoices}</summary>
          <ul>{L.choices.map((x, i) => <li key={i}>{x}</li>)}</ul>
          <button className="footer-btn" onClick={clearLocal} style={{ marginTop: 8 }}>
            {L.clearBtn}
          </button>
        </details>

        <details>
          <summary>👶 {L.hMinors}</summary>
          <p>{L.minors}</p>
        </details>

        <details>
          <summary>🛡️ {L.hSafety}</summary>
          <p>{L.safety}</p>
        </details>
      </div>
    </Modal>
  );
}