import React from "react";
import Modal from "./Modal.jsx";

const LOCAL_KEYS = [
  "activeReminder",
  "doseSchedule",
  "takenTimestamps",
  "medsTaken",
  "nextDoseTime",
  "overdueMap",
  "lastCheerMilestone",
  "isSupporter",
  "ownerId",
  "ownerName",
  "supporterName",
];

export default function PrivacyPolicy({ isOpen, onClose, language }) {
  const t = {
    English: {
      title: "Privacy Policy",
      quick:
        "Pill-AI does not collect or store personal data about you. Your questions are processed anonymously. Do not rely on Pill-AI for medical decisions—always consult a health professional.",
      weCollect: [
        "No account is required. We do not ask for your name, email, or address.",
        "No medicine history is uploaded to our servers by the app.",
        "We do not intentionally collect any sensitive personal information.",
      ],
      onDevice: [
        "Reminder setup (medicine name, duration/long-term, times per day, chosen times).",
        "Dose schedule and which doses you marked as taken.",
        "Progress counters and milestones for cheering.",
        "Support/cheer membership info you joined or created (IDs/names you entered).",
      ],
      notifications: [
        "To send reminders, the app asks your browser/phone for permission to show notifications.",
        "A push token is generated by your browser for this device. It is used only to deliver reminders you asked for.",
        "You can revoke notification permission anytime in your browser/device settings.",
      ],
      sharing: [
        "We do not sell your data.",
        "Cheer Squad links you share are private to people you send them to.",
        "Aggregated, de-identified stats may be used to improve the prototype.",
      ],
      choices: [
        "You can delete on-device data below (localStorage).",
        "You can disable notifications in your browser/device settings.",
        "You can remove supporters and invites at any time.",
      ],
      minors:
        "Pill-AI is a prototype for education/research. If you are under 16, use it with a parent/caregiver.",
      safety:
        "Content is informational only and based on trusted NZ sources (e.g., Medsafe). It does not replace professional advice.",
      clearBtn: "🗑️ Clear my app data (local)",
      clearDone: "Local app data cleared.",
      confirm:
        "Clear local app data for this browser? This will reset reminders, progress, and supporter info stored on this device.",
    },
  };

  const L = t[language] || t.English;

  function clearLocal() {
    if (!window.confirm(L.confirm)) return;
    try {
      LOCAL_KEYS.forEach((k) => localStorage.removeItem(k));
      alert(L.clearDone);
    } catch (e) {
      console.warn("Clear local failed:", e);
    }
  }

  return (
    <Modal isOpen={isOpen} onClose={onClose} title={L.title}>
      <div className="policy">
        <p style={{ marginTop: 0 }}>{L.quick}</p>

        <details open>
          <summary>✅ What we collect</summary>
          <ul>{L.weCollect.map((x, i) => <li key={i}>{x}</li>)}</ul>
        </details>

        <details>
          <summary>📱 What stays on your device</summary>
          <ul>{L.onDevice.map((x, i) => <li key={i}>{x}</li>)}</ul>
          <p style={{ marginTop: 8, fontSize: 13, color: "#666" }}>
            Stored using your browser’s localStorage on this device only.
          </p>
        </details>

        <details>
          <summary>🔔 Notifications & permissions</summary>
          <ul>{L.notifications.map((x, i) => <li key={i}>{x}</li>)}</ul>
        </details>

        <details>
          <summary>🤝 Sharing & third parties</summary>
          <ul>{L.sharing.map((x, i) => <li key={i}>{x}</li>)}</ul>
        </details>

        <details>
          <summary>⚙️ Your choices & control</summary>
          <ul>{L.choices.map((x, i) => <li key={i}>{x}</li>)}</ul>
          <button className="footer-btn" onClick={clearLocal} style={{ marginTop: 8 }}>
            {L.clearBtn}
          </button>
        </details>

        <details>
          <summary>👶 Minors</summary>
          <p>{L.minors}</p>
        </details>

        <details>
          <summary>🛡️ Safety disclaimer</summary>
          <p>{L.safety}</p>
        </details>
      </div>
    </Modal>
  );
}